# Generated by Django 3.2.4 on 2023-09-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alumnos_fk_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='fk_genero',
        ),
        migrations.CreateModel(
            name='alumno_has_genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_alumno', models.ForeignKey(db_column='fk_alumno', on_delete=django.db.models.deletion.CASCADE, to='api.alumnos')),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
            options={
                'db_table': 'alumno_has_genero',
            },
        ),
    ]
